name: Deploy to the hosting FTP

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    name: 🎉 Build->Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Use composer
        run: composer install

      - name: Create env file
        run: |
          touch .env
          echo APP_NAME="ProgMan.site" >> .env
          echo APP_KEY=$(php artisan key:generate --force --show) >> .env
          echo APP_DEBUG=true >> .env
          echo DB_CONNECTION=mysql >> .env
          echo DB_HOST=${{ vars.DB_HOST }} >> .env
          echo DB_DATABASE=${{ vars.DB_DATABASE }} >> .env
          echo DB_USERNAME=${{ vars.DB_USER }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo TELEGRAM_BOT_API_TOKEN=${{ secrets.TELEGRAM_BOT_API_TOKEN }} >> .env
          echo TELEGRAM_BOT_LOGIN=${{ vars.TELEGRAM_BOT_LOGIN }} >> .env
          echo TELEGRAM_ADMIN_CHAT_ID=${{ vars.TELEGRAM_ADMIN_CHAT_ID }} >> .env
          echo TELEGRAM_ADMIN_ACCOUNTS_LIST=${{ vars.TELEGRAM_ADMIN_ACCOUNTS_LIST }} >> .env
          cat .env
      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: Removing of extra files
        run: |
          rm -rf .ebextensions .platform resources/js

      - name: 📂 Sync files
        id: ftp_deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.FTP_HOST }}
          username: ${{ vars.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}

      - name: Sanding the result notification through Telegram
        env:
          GET_PARAMS: printf %s 'chat_id={{vars.TELEGRAM_DEPLOY_NOTICE_RECIPIENT_ID}}&text=SUCCESS!\n${{github.event.head_commit.message}}'|jq -sRr @uri)
        run: |
          curl https://api.telegram.org/bot{{secrets.TELEGRAM_DEPLOY_NOTIFIER_BOT_TOKEN}}/sendMessage?chat_id={{TELEGRAM_DEPLOY_NOTICE_RECIPIENT_ID}}&text=SUCCESS

  debug:
    name: Check failure
    needs: build-deploy
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: Debug
        uses: actions/checkout@v4
        run: ./debug

      - name: Sanding the result notification through Telegram
        env:
          GET_PARAMS: printf %s 'chat_id={{vars.TELEGRAM_DEPLOY_NOTICE_RECIPIENT_ID}}&text=FAILED!\n${{github.event.head_commit.message}}\n\n${{toJson(steps)}}'|jq -sRr @uri)
        run: |
          curl https://api.telegram.org/bot{{secrets.TELEGRAM_DEPLOY_NOTIFIER_BOT_TOKEN}}/sendMessage?$GET_PARAMS

