name: Deploy to the hosting FTP

on:
  push:
    branches: [ "main" ]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Use composer
        run: |
          composer install

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build
      - name: Create env file
        run: |
          touch .env
          ex_env=$(<.env.example)
          while IFS= read -r line; do
            line=${line%$'\r'}
            if [[ $line =~ ^([A-Z][A-Z0-9_]{2,})=(.*)$ ]]; then
              VAR=${BASH_REMATCH[1]}
              VAL=${BASH_REMATCH[2]}
              VAR_NAME="vars.$VAR"
              VAR_VAL=${{$VAR_NAME}}
              echo "checking var name $VAR_NAME\n"
              if [[ VAR_VAL != "" ]]; then
                VAL=VAR_VAL
                echo "$VAR - is set to .env from github vars\n"
              fi
              SECRET_NAME="secrets.$VAR"
              SECRET_VAL=${{$SECRET_NAME}}
              echo "checking var name $SECRET_NAME\n"
              if [[ $SECRET_VAL != "" ]]; then
                VAL=vars[$VAR]
                echo "$VAR - is set to .env from github secrets\n"
              fi
              if [[ $VAR==APP_KEY ]]; then
                VAL=$(php artisan key:generate --force --show)
                echo "$VAR - has been generated using Laravel artisan\n"
              fi
              echo "$VAR=$VAL" >> .env
            else
              echo $line >> .env
            fi
          done <<<"$ex_env"
          cat .env
      - name: Removing of extra files
        run: |
          rm -rf .ebextensions .platform resources/js

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.FTP_HOST }}
          username: ${{ vars.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
